name = "Track Order Hub"
client_id = "bb434ba155e0204b0fdd80e2b604a364"
application_url = "https://track-order-hub-production.up.railway.app"
embedded = true
handle = "track-order-hub"
web_directories = ["."]

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_orders"

[auth]
redirect_urls = [
  "https://track-order-hub-production.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2026-07"
